---
- name: Fail if required vars are not set
  fail:
  when: >
    name == None or name|length == 0

- shell: systemctl list-unit-files --no-legend "{{ name }}" | awk '{print $2}'
  register: systemctl_result
  when: (name|default(None) != None)
  changed_when: false

- set_fact:
    systemd_unit_state: systemctl_result.stdout
    systemctl_result: !!null

- shell: systemctl enable "{{ name }}"
  when: (name|default(None) != None) and (enabled|default(None) == True) and systemd_unit_state != 'enabled'

- shell: systemctl disable "{{ name }}"
  when: (name|default(None) != None) and (enabled|default(None) == False) and systemd_unit_state != 'disabled'

- shell: systemctl mask "{{ name }}"
  when: (name|default(None) != None) and (masked|default(None) == True) and systemd_unit_state != 'masked'

- shell: systemctl unmask "{{ name }}"
  when: (name|default(None) != None) and (masked|default(None) == False) and systemd_unit_state == 'masked'

- set_fact:
    systemd_unit_state: !!null
